#!/usr/bin/env bash

__ScriptVersion="1.0"

nvimdir=~/.local/share/nvim/local-plugs/

create_git() {
	dir=$(echo $1|cut -d'.' -f1)
	cd $nvimdir$dir

	git init $nvimdir$dir 1>/dev/null
	echo initializing $nvimdir$dir
	git add plugin/${files[i]} 2>/dev/null
	git commit -m 'Add ${files[i]}' >/dev/null

	cd $nvimdir
}

create_dir() {
	files=$1
	newdir=$(echo $1}|cut -d'.' -f1)
	mkdir -p $newdir/plugin
	mv $1 $newdir/plugin/
}

create_file() {
	mkdir -p $nvimdir
	local files=()

	cd $nvimdir

	wget $1 2>/dev/null
	echo Downloading $filename
	if [[ $? -ne 0 ]]; then
		rm filename
		exit 2
	fi
	files+=($filename)
}

remove_plugs() {
	
}

function usage () {
	echo "Usage :  $0 [options] [--]

    Options:
    -h|help       Display this message
    -v|version    Display script version
    -r|remove     Remove local plugins"

}

while getopts ":hv" opt
do
  case $opt in

	h|help)
		usage
		exit 0
		;;

	v|version)
		echo "$0 -- Version $__ScriptVersion"
		exit 0
		;;

	r|remove)
		remove_plugs
		exit 0
		;;

	* )  echo -e "\n  Option does not exist : $OPTARG\n"
		 usage
		 exit 1
		 ;;

  esac    # --- end of case ---
done
shift $(($OPTIND-1))

if [[ ($# -gt 0 && $(command -v git)) ]]; then
	vim_files=($@)
	plugins=()
	for (( i = 0; i < ${#vim_files[@]}; i++ )); do
		filename=$(echo ${vim_files[i]}|rev|cut -d'/' -f1|rev)
		create_file ${vim_files[i]}
		create_dir  $filename
		create_git  $filename
		plugins+=("Plug 'file://$nvimdir$dir'\n")
	done
	echo -e "\n${plugins[@]}"
elif [[ ($# -gt 0) ]]; then
	echo git not installed
else
	echo $0 requires input vim plugins
	exit 2
fi
